---
version: '2'


services:

  composer:
    build:
        context: ./build/php
    container_name: composer
    entrypoint:
      - composer
    working_dir: /code
    volumes:
      - "$PWD:/code"

  develop:
    build:
        context: ./build/php
    container_name: develop
    working_dir: /code
    command: sleep 100d
    volumes:
      - "$PWD:/code"